services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio@admin
      MINIO_ROOT_PASSWORD: minio@admin
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "boards_and_cats"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "9979"
    volumes:
      - ./db:/var/lib/postgresql/data