CREATE TABLE tb_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    display_name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    phone varchar(255) NOT NULL,
    cpf varchar(255) NOT NULL UNIQUE
);

CREATE TABLE tb_address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street varchar(255) NOT NULL,
    number varchar(10),
    neighborhood varchar(255),
    city varchar(255) NOT NULL,
    state varchar(255) NOT NULL,
    zip varchar(255) NOT NULL,
    complement varchar(255),
    user_id bigint NOT NULL,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);

CREATE TABLE tb_payment_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fk_payment_method_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);

CREATE TABLE tb_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE tb_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    description varchar(1024),
    price numeric(38,2) NOT NULL,
    category_id bigint NOT NULL,
    mechanics varchar(255),
    players varchar(255),
    editor varchar(255),
    promo boolean NOT NULL,
    stock integer NOT NULL,
    image_url varchar(255),
    duracao varchar(255),
    idade_recomendada varchar(255),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES tb_category(id)
);

CREATE TABLE tb_product_images (
    product_id bigint NOT NULL,
    image_url varchar(255) NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES tb_product(id) ON DELETE CASCADE
);

CREATE TABLE tb_coupon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL UNIQUE,
    discount_value numeric(38,2) NOT NULL,
    valid_until date,
    active boolean
);

CREATE TABLE tb_cart (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);

CREATE TABLE tb_cart_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    price_at_save numeric(38,2) NOT NULL,
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES tb_cart(id) ON DELETE CASCADE
);

CREATE TABLE tb_wishlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES tb_product(id) ON DELETE CASCADE,
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id)
);

CREATE TABLE tb_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    status varchar(255) NOT NULL,
    total numeric(38,2) NOT NULL,
    shipping numeric(38,2) DEFAULT 0.00,
    discount numeric(38,2) DEFAULT 0.00,
    tracking_code varchar(255),
    user_id bigint,
    street varchar(255),
    number varchar(255),
    neighborhood varchar(255),
    city varchar(255),
    state varchar(255),
    zip varchar(255),
    description varchar(255),
    client_name varchar(255),
    client_cpf varchar(255),
    client_phone varchar(255),
    client_email varchar(255),
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE SET NULL
);

CREATE TABLE tb_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    subtotal numeric(38,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES tb_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES tb_product(id)
);
