ALTER TABLE tb_user ADD COLUMN active boolean DEFAULT false;
ALTER TABLE tb_user ADD COLUMN role varchar(255) DEFAULT 'USER';

UPDATE tb_user SET active = true;

CREATE TABLE tb_order_document (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    file_name varchar(255) NOT NULL,
    minio_path varchar(1024) NOT NULL,
    content_type varchar(255) NOT NULL,
    uploaded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_document_order FOREIGN KEY (order_id) REFERENCES tb_order(id) ON DELETE CASCADE
);

CREATE TABLE tb_operation_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email varchar(255) NOT NULL,
    operation varchar(255) NOT NULL,
    details text,
    timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
