-- ============================================================================
-- CRIAÇÃO DA TABELA DO CAROUSEL E MIGRAÇÃO DE CAMINHOS DE MÍDIA
-- ============================================================================

-- 1. Criação da tabela de itens do carousel/banner principal
CREATE TABLE tb_carousel_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint,
    image_url varchar(255) NOT NULL,
    alt varchar(255) NOT NULL,
    CONSTRAINT fk_carousel_item_product FOREIGN KEY (product_id) REFERENCES tb_product(id) ON DELETE SET NULL
);

-- 2. Insere os banners iniciais padronizados com o novo path do MinIO
INSERT INTO tb_carousel_item (product_id, image_url, alt) VALUES
(3, '/media/bannerpandemic.png', 'Pandemic - Salve o mundo'),
(9, '/media/bannerdistilled.png', 'Distilled - Mestre da Destilação'),
(1, '/media/bannerterra.png', 'Terra Mystica - Estratégia Pura'),
(5, '/media/bannergloom.png', 'Gloomhaven - Aventura Épica');

-- 3. Atualiza os caminhos das imagens existentes de /images/... para /media/{filename}
UPDATE tb_product 
SET image_url = '/media/' || substring(image_url from '[^/]+$')
WHERE image_url IS NOT NULL AND image_url LIKE '%/%';

UPDATE tb_product_images 
SET image_url = '/media/' || substring(image_url from '[^/]+$')
WHERE image_url IS NOT NULL AND image_url LIKE '%/%';
