spring.application.name=server
server.address=localhost
server.port=8080

spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:postgresql://localhost:5433/boards_and_cats
spring.datasource.username=postgres
spring.datasource.password=9979
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# Minio configuration
minio.endpoint=http://localhost:9000
minio.access-key=minio@admin
minio.secret-key=minio@admin
minio.bucket-name=boards-and-cats-documents

# Spring Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuracoes do sandbox do Melhor Envio
melhorenvio.sandbox.url=https://sandbox.melhorenvio.com.br/api/v2
melhorenvio.token=SUA_CHAVE_AQUI
melhorenvio.email=pepper.pbco@gmail.com
shipping.origin.cep=85501296

# Increase maximum file upload size to support high-res banners and images
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB